baseURL = "https://artificialtwin.gitlab.io/alphaMale/diambra/diambraArenaDocs/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "DIAMBRA Arena Docs"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[markup.goldmark.renderer]
unsafe= true
[markup.goldmark.extensions]
linkify = false

[params]
  #editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "DIAMBRA Arena Documentation"
  author = "Alessandro Palmas"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "diambra"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "DIAMBRA Arena Docs"
weight = 1
languageName = "English"
landingPageURL = "./"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-globe'></i> Website"
identifier = "website"
url = "https://diambra.ai"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Repo"
identifier = "github"
url = "https://github.com/diambra/diambraArena"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-twitch'></i> Twitch UPDATE LINK"
url = "twitch"
weight = 15

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-discord'></i> Discord"
url = "https://discord.gg/tFDS2UN5sv"
weight = 14

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-youtube'></i> YouTube UPDATE LINK"
url = "/credits"
weight = 21

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Linkedin"
url = "https://www.linkedin.com/company/diambra"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-heart'></i> Support"
identifier = "support"
url = "https://www.paypal.com/donate?token=9jYa1y3F4jOACFWJI8BVqOSfDh5yNiN-TC9rn_AwNfo1391bRN4F_la1yBg62ugQTj0ZWmVDQC6TB0UY"
weight = 30

