baseURL = "https://artificialtwin.gitlab.io/alphaMale/diambra/diambraArenaDocs/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "DIAMBRA Arena Docs"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[markup.goldmark.renderer]
unsafe= true

[params]
  #editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "DIAMBRA Arena documentation"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "diambra"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "DIAMBRA Arena Docs"
weight = 1
languageName = "English"
landingPageURL = "./"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/diambra/DIAMBRAenvironment"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "showcase"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-heart'></i> Support"
identifier = "support"
url = "https://www.paypal.com/donate?token=nGXpYEIW16U7h-prozHCv3N0hAqkruAmnJ2xummvIoc8cQ5Deapl4dCpZn5kD9xIAtD2TKLf-E3sv15p"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
