baseURL = "https://docs.diambra.ai"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "DIAMBRA Docs"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[markup.goldmark.renderer]
unsafe= true
[markup.goldmark.extensions]
linkify = false

[params]
  #editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Official documentation for DIAMBRA, the platform where coders create AI agents to compete in video games tournaments."
  keywords = "Documentation, Reinforcement Learning, Deep Reinforcement Learning, AI Tournaments, Video Games Environments, RL Environments, DIAMBRA, Dueling AI Arena, DIAMBRA Documentation, AI Competitions, Artificial Intelligence"
  author = "DIAMBRA Team"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "diambra"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "DIAMBRA Docs"
weight = 1
languageName = "English"
landingPageURL = "./"
landingPageName = "<i class='fas fa-home'></i> Home"

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-globe'></i> Website"
identifier = "website"
url = "https://diambra.ai"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "github"
url = "https://github.com/diambra/"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-discord'></i> Discord"
url = "https://discord.gg/tFDS2UN5sv"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-twitch'></i> Twitch"
url = "https://www.twitch.tv/diambra_ai"
weight = 13

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Linkedin"
url = "https://www.linkedin.com/company/diambra"
weight = 14

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-youtube'></i> YouTube"
url = "https://www.youtube.com/c/diambra_ai"
weight = 15

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
identifier = "twitter"
url = "https://twitter.com/diambra_ai"
weight = 16

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-heart'></i> Support"
identifier = "support"
url = "https://streamlabs.com/diambra_ai/tip"
weight = 30

