name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
  repository_dispatch:
    types: [rebuild-deploy]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.event_name == 'repository_dispatch'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: docs.diambra.ai
